# see http://matthew.mceachen.us/blog/how-to-test-your-rails-application-with-travis-ci-on-different-databases-engines-1220.html
# for sample setup
language: ruby
rvm:
  - "2.0.0"
before_script:
  - psql -c 'create database ticketeer-test;' -U postgres
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
